### ISSUE TITLE
SSD Percentage Used

### ISSUE THREAD

**Issue by muperman** [Sheridan/smartctl_exporter#4]
Hello! Thank you for you work!

I want to monitor "Percentage Used" parameter in my prometheus server, but can't find this metric.
Is it possible to use it?

**Comment by Sheridan** [comment]
If the device has such a metric, then it will be in smartctl_device_statistics or smartctl_device_attribute. Look in the tags for the relevant metric name, please.

There are also smartctl_device_block_size, smartctl_device_capacity_blocks metrics
