### ISSUE TITLE
Drive replacement killed the exporter

### ISSUE THREAD

**Issue by riddley** [Sheridan/smartctl_exporter#5]
Thanks to your exporter I was able to spot a failing drive. When I replaced it, the exporter doesn't log any errors, but the /metrics route complains about the change in model and serial number. How can I fix it?

Thanks for the exporter btw! It's great! Do you have a grafana dashboard for it?

**Comment by riddley** [comment]
So this is abandonware then?

**Comment by Sheridan** [comment]
No, just 2020 :(

**Comment by Sheridan** [comment]
Possibly fixed in version 0.6
