### ISSUE TITLE
[Error] Fake S.M.A.R.T. data reading error: open sda.json: no such file or directory

### ISSUE THREAD

**Issue by smallops** [Sheridan/smartctl_exporter#7]
启动报错
```shell
[Debug] Parsed options: {{:9633 /metrics %!s(bool=true) /usr/sbin/smartctl 120s 2m0s [/dev/sda]}}
[Error] Fake S.M.A.R.T. data reading error: open sda.json: no such file or directory
panic: runtime error: index out of range

goroutine 22 [running]:
main.(*SMARTctlInfo).mineVersion(0xc0000b4eb8)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/smartctlinfo.go:46 +0x92a
main.(*SMARTctlInfo).Collect(...)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/smartctlinfo.go:35
main.SMARTctlManagerCollector.Collect(0xc00023c060)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/main.go:34 +0x1b0
github.com/prometheus/client_golang/prometheus.DescribeByCollect.func1(0x9688c0, 0xca8930, 0xc00023c060)
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/vendor/src/github.com/prometheus/client_golang/prometheus/collector.go:90 +0x3b
created by github.com/prometheus/client_golang/prometheus.DescribeByCollect
	/mnt/Sheridan/sheridan/sheridan/smartctl_exporter/vendor/src/github.com/prometheus/client_golang/prometheus/collector.go:89 +0x75
```
没有报错,json输出正常
/usr/sbin/smartctl --json --xall /dev/sda > /tmp/sda.json
smartctl版本是7+

smartctl 7.0 2018-12-30 r4883 [x86_64-linux-3.10.0-957.27.2.el7.x86_64] (local build)
Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

smartctl comes with ABSOLUTELY NO WARRANTY. This is free
software, and you are welcome to redistribute it under
the terms of the GNU General Public License; either
version 2, or (at your option) any later version.
See http://www.gnu.org for further details.

smartmontools release 7.0 dated 2018-12-30 at 14:47:55 UTC
smartmontools SVN rev 4883 dated 2018-12-30 at 14:48:54
smartmontools build host: x86_64-redhat-linux-gnu
smartmontools build with: C++98, GCC 4.8.5 20150623 (Red Hat 4.8.5-39)
smartmontools configure arguments: '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--with-selinux' '--with-libcap-ng=yes' '--with-libsystemd' '--with-systemdsystemunitdir=/usr/lib/systemd/system' '--sysconfdir=/etc/smartmontools/' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CXXFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro ' 'CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig

**Comment by Sheridan** [comment]
I have now made a script specially for this that prepares files for testing.
```
sudo ./collect_fake_json.sh
```
